### ISSUE TITLE
Function Documentation Review

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#113]
@atorus-research/xportr-development-team I'm working my way through reviewing each of the functions.   Trying to identify parts to update and larger questions that can help simplify this work.  Try to complete review tomorrow and get this into a more readable state, feel free to comment on anything :) 

# Big Questions
* Define an appropriate metadata object? - It is either a dataframe built from a specification file or a metacore object.  I like the phrase appropriate metadata object and we should use that rather than dataframe or metacore object.
* Shall we use the `@details` section to list out certain assumption used in the function.   Some functions have assumptions in them and I think this is needed, but we should codify this in the wiki!
* Establish common phrasing for each xportr function arguments, i.e. `.df`, `metacore` (to be changed), `domain`, `verbose`.  All should read the same as they essentially do the same thing in each function.
* I think each function should have examples of warnings and messaging in the examples.

## xportr_type()

* I think the Current assumptions section should get moved in the details section.  I'm not sure what `columns_meta` but we should revisit.
* I think this function is closer to our gold standard for how our documenation should read

![image](https://github.com/atorus-research/xportr/assets/10111024/b7de03b3-6b61-41cc-a295-0a724cc8d1b4)

## xportr_length

Update Title:  Assigns a SAS Length to a Variable Attribute
Update Details:  Variable Level Metadata has a certain connotation in clinical reporting - It should read Assigns a SAS length from the Length Column from an appropriate metatdata source
Change Metacore Argument: The argument should be metadata and it can take in dataframe object built from a spec file or a metacore object (link to metacore)
Domain:  What is a Domain?  We should say this refers to the Dataset Column in the appropripate metadata file
Verbose:  We should highlight that the user can receive feedback around the use of the verbose argument printed out to the console.  The use of stop will cause the function to not work, etc. 
Update Value - Each variable that has a Length specified in the appropriate metadata object will have it applied as a `SASlength` attribute`

Examples:  Can we showcase examples with printed out messages for warn and stop
![image](https://github.com/atorus-research/xportr/assets/10111024/af541362-d8b6-438e-b1ae-22a3afb2d5de)

## xportr_label()

We should avoid the phrase variable level metadata.

Examples: Can we showcase examples with printed out messages for warn and stop
![image](https://github.com/atorus-research/xportr/assets/10111024/13966fee-3c22-43f7-8a19-cd4fc1032f07)

**Comment by bms63** [comment]
I started to put together some conventions for roxygen headers: https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers

**Comment by cpiraux** [comment]
I was thinking to add in conventions for roxygen headers for example to try to follow define xml specification for metadata example. When we arrive at the stage of xpt, normally the specs should be closed to define xml specification.

The Type should be: text, integer, float, datetime, date, time,  (partialdate, partialtime, partialdatetime,  incompletedatetime, durationdatetime, intervaldatetime: not very common so could skip them in example)
Character type are: text, datetime, date, time
Numeric type are: integer, float

For the length, if the type is datetime, date or time then length should be left blank.

What do you think?

**Comment by bms63** [comment]
@cpiraux also is there other gaps in functions or additional functions needed to help us build a complete xpt.  I think you and @kaz462 have the most experience in our group for submissions.

**Comment by bms63** [comment]
> It would be interesting to have a function that sort the records by key variables (column in dataset metadata) and check the uniqueness of the key.
> 
> Define-XML Version 2.0 Completion Guidelines pg 11 ![image](https://user-images.githubusercontent.com/69685640/237710071-5b8f78b5-1124-4700-a9fe-3d1d0af0c741.png)

So like an `xportr_key` or should we allow `xportr_order` to have a key argument that you can turn on/off?
