### ISSUE TITLE
Improve Error Message Feedback

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#117]
Hi @atorus-research/xportr-development-team 

I think in this release we should improve the error messaging when a user invokes `stop` in the xportr functions.  This would make the deep-dive vignette much richer as well.

Currently, we get:

![image](https://github.com/atorus-research/xportr/assets/10111024/c6e9ae63-e4c0-4c4f-bcd5-a27435fbe99c)

But I think we could make this cleaner and give user feedback that they have chosen `stop` in the code and that xportr will not apply any labels to their dataframe - even though only one is missing in this example.

There was a mention of `rlang::abort` being used.  Anyone want to take this on!?!

**Comment by kaz462** [comment]
It seems `rlang::abort` is used in this package.
@bms63 Could you please provide a reproducible example for your error message? I tried an example but got clean error message -
``` r
library(xportr)
adsl <- data.frame(
    USUBJID = c(1001, 1002, 1003),
    SITEID = c(001, 002, 003),
    AGE = c(63, 35, 27),
    SEX = c("M", "F", "M")
)

metacore <- data.frame(
    dataset = "adsl",
    variable = c( "SITEID", "AGE", "SEX"),
    label = c( "Study Site Identifier", "Age", "Sex")
)

adsl1 <- xportr_label(adsl, metacore, domain="adsl", verbose = "stop")
#> 
#> ── Variable labels missing from metadata. ──
#> 
#> ✔ 1 labels skipped
#> Error in `xportr_logger()`:
#> ! Variable(s) present in dataframe but doesn't exist in `metadata`.
#> ✖ Problem with `USUBJID`
#> Backtrace:
#>     ▆
#>  1. └─xportr::xportr_label(adsl, metacore, domain = "adsl", verbose = "stop")
#>  2.   └─xportr::label_log(miss_vars, verbose)
#>  3.     └─xportr::xportr_logger(...)
#>  4.       ├─base::do.call(log_fun, list(message, ...))
#>  5.       └─rlang (local) `<fn>`(`<chr>`)
```

<sup>Created on 2023-05-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
