### ISSUE TITLE
Missing articles in documentation

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#12]
Hey gang, I was reading the front page https://atorus-research.github.io/xportr/index.html and got to the section it says "Please check out the 3 articles within the Articles Tab:". I couldn't find these pages - are they still being added or did I just miss them somewhere?

**Comment by bms63** [comment]
Hey Ross,  I think we had high hopes to write those articles and forgot to remove their reference in the readme.  If xportr looks to be the way to go, then maybe we should double back and write those articles @elimillera !
