### ISSUE TITLE
xportr_  function to sort the rows by key

### ISSUE THREAD

**Issue by cpiraux** [atorus-research/xportr#125]
Add a function to sort the rows in a dataframe based on a key variable. The key variables can be found in the dataset portion of the metadata, which is the same section where the dataframe label is located.

Check:
The key variables should uniquely identify each record. This means that if we perform a distinct operation based on these variables, only one record should be found.
If the key is not unique, it is very helpful to create a dataframe containing the non-unique records. This will help identify additional variables that can be included in the key variables to achieve uniqueness.

**Comment by bms63** [comment]
metacore is going to do this for us!
