### ISSUE TITLE
This check the output file name not the data value in the data frame

### ISSUE THREAD

**Issue by djhbs** [atorus-research/xportr#126]
https://github.com/atorus-research/xportr/blob/231e959b84aa0f1e71113c85332de33a827e650a/R/write.R#LL33C1-L33C82
Could you please confrim this check refer to the output file name not the data value?
For the file name, if the DM_F can be used when the `strict_checks = FALSE`，and the DM_F means the full SDTM  that contains the parent DM and SUPPDM
Thank you very much.

**Comment by bms63** [comment]
@cpiraux So we can close this issue as out of scope and make an additional issue regarding underscores?
