### ISSUE TITLE
Bug: Outputting issues with variables in every domain

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#128]
Look in 84-deepdive  branch for data and specs

```
library(dplyr)
library(xportr)

spec_loc <- here::here("example_data_specs", "TDF_ADaM_Pilot3.xlsx")

var_spec <- readxl::read_xlsx(spec_loc, sheet = "Variables") %>% 
  mutate(Label = if_else(Variable == "TRTSDT", 
                         "Date of First Exposure to Treatment Date of First Exposure to Treatment", Label))

adsl_loc <- here::here("example_data_specs", "adsl.xpt")

adsl <- haven::read_xpt(adsl_loc) %>% 
  metatools::remove_labels() 

adsl_lbl <- xportr_label(adsl, var_spec, "ADSL", verbose = "warn")
```

Should just be one `TRTSDT`

![Image](https://github.com/atorus-research/xportr/assets/10111024/6af7888b-6c6d-40d3-8d79-71e815a54e23)

If time given, then look into other xportr functions

**Comment by averissimo** [comment]
This also risks the functions themselves as it might not be able to find the column with the metadata (example: No label column in `xportr_label`)

## Example of spec file from pilot 3

![image](https://github.com/atorus-research/xportr/assets/211358/7f993f8a-f3c0-4c0e-98c9-068a4632304d)

## Default values

![image](https://github.com/atorus-research/xportr/assets/211358/b8ec2e5e-3ad2-4dd8-92e6-2964cf4db5ee)

**Comment by cpiraux** [comment]
In addition to the column names case in metadata, we could check the mapping between the metadata and the expected metadata structure. 

The column names in the specifications file may differ depending on the template used for the specifications. 

It would be valuable to provide guidance to the user regarding which part of the metadata does not align with the expected metadata structure, what is the expected structure, and how to update the metadata to conform to the expected structure.

For instance, in the P21C template, the column name is 'Data Type,' whereas the expected value is 'type.'

**Comment by bms63** [comment]
I think `xportr.options` is supposed to allow us to change `variable` to `Variable`.  I was using this in my vignette, but honestly I find it a little confusing to use.
