### ISSUE TITLE
Need to add 'dateTime' and 'Time' as characer types in zzz.R

### ISSUE THREAD

**Issue by adchan11** [atorus-research/xportr#143]
### What happened?

We're getting errors when the DAP M3 metacore object, in the type column, when some DTC variables are classified as 'dateTime' and then since it's not in zzz.R, it is not coerced properly and then becomes NA when written as an xpt. Can we add dateTime and Time as additional strings to consider?

**Comment by EeethB** [comment]
Looks like this was addressed in #80. Thanks to @cpiraux for catching this in that issue - https://github.com/atorus-research/xportr/pull/80#issuecomment-1543927950

**Comment by adchan11** [comment]
Thank you! I will close this issue and follow #80
