### ISSUE TITLE
Feature Request: Implement messaging for `xportr_format()`

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#164]
### Feature Idea

We currently lack messaging for the `xportr_format()` function.

Ideas
* Messages for lack of formats for DT and DTM variables
* Messaging for poorly formed formats in spec files
* ?

**Comment by EeethB** [comment]
May be helpful to reference `xportr_write()` format messaging

**Comment by sophie-gem** [comment]
Rules to implement:
- [ ] if a variable name ends in 'DT' or 'DTM' or 'TM' then there should be an associated format.
- [ ] if variable is character then the format should have a `$` prefix and remaining length must be <= 31.
- [ ] if variable is numeric then the format should not have a `$` prefix and length must be <= 32.
- [ ] Should either be included in the expected formats list or follow a specific pattern.
- [ ] Any others??

**Comment by sophie-gem** [comment]
I've noticed that in the `utils-xportr.r` script, in the creation of `expected_formats` the `E8601TZ` formats currently contain spaces due to missing either `sep=""` or not using `paste0()`.

<img width="300" alt="image" src="https://github.com/atorus-research/xportr/assets/90790226/46fd4476-6210-40c5-ac68-df66946d6939">

Is this a new issue or should this be dealt with as part of this current issue?

**Comment by sophie-gem** [comment]
What should happen with `class(<var>)[1] = "Date"`? Currently I'm not checking for this in the rules.

**Comment by sophie-gem** [comment]
Are we happy with the list of expected formats used in the `xportr_write()` tests?

- I'm assuming we've gone through and checked these against the SAS website? 
- Is this something you'd like me to review, or have we already reviewed this?

**Comment by sophie-gem** [comment]
Currently the checks are carried out on each variable individually as the format is applied - is this going to cause issues with speed / efficiency?

**Comment by sophie-gem** [comment]
Also, I don't know if the code `paste("E8601DT", 16:26, ".", 0:6, sep = "")` in the `expected_formats` is having the intended output? 

<img width="400" alt="image" src="https://github.com/atorus-research/xportr/assets/90790226/d1366680-61d2-46c3-8b02-9e15c7da6729">

I think we're wanting all combinations of 16-26 with 0-6 but in reality we're only getting the second lot of numbers one-to-one against the first and recycled as the length implies...

**Comment by sophie-gem** [comment]
Apologies for all the qs! It may be worth discussing this in our next meeting.

**Comment by bms63** [comment]
Thanks Sophie!  I think we should break these into smaller issues to fix/address/investigate.  Unless addressing them is really important to your issue/PR.   If they can wait, do you mind putting into separate PRs please crosslinking to this issue.

**Comment by bms63** [comment]
I think the eso thing was addressed in this issue: https://github.com/atorus-research/xportr/issues/76

**Comment by bms63** [comment]
@sophie-gem do you think we can finish this by the end of the week?

**Comment by sophie-gem** [comment]
If 'end of this week' means by the end of Sunday, I should be able to. If you mean by Friday, there is a high change I won't be able to meet that. 

I think I'm close to opening a PR, just need to run the standard checks through it and merge in the most recent main branch to avoid any merge conflicts.

**Comment by bms63** [comment]
Sunday is good - even if it is just a PR that we discuss and make updates in that is great!!
