### ISSUE TITLE
where to find ADaM_spec.xlsx file 

### ISSUE THREAD

**Issue by tataphani** [atorus-research/xportr#17]
As per this it is looking for the ADaM_spec.xlsx file , can you please help me to point it out where to find or even the sample of how the document would look like so that I can replicate how you are doing , I am making a presentation soon showcasing your package , can you please help me 

The first example involves an ADSL data set in the .sas7bdat format with associated specification in the .xlsx format.

adsl <- haven::read_sas("inst/extdata/adsl.sas7bdat")

var_spec <- readxl::read_xlsx("inst/specs/ADaM_spec.xlsx", sheet = "Variables") %>%
  dplyr::rename(type = "Data Type") %>%
  rlang::set_names(tolower)
  
data_spec <- readxl::read_xlsx("inst/specs/ADaM_spec.xlsx", sheet = "Datasets") %>%
  rlang::set_names(tolower) %>%
  dplyr::rename(label = "description")
  
adsl %>%
  xportr_type(var_spec, "ADSL", "message") %>%
  xportr_length(var_spec, "ADSL", "message") %>%
  xportr_label(var_spec, "ADSL", "message") %>%
  xportr_df_label(data_spec, "ADSL") %>%
  xportr_write("adsl.xpt")

**Comment by tataphani** [comment]
sorry i found it

**Comment by elimillera** [comment]
Hey @tataphani Looks like you found it but you can pull this file down with the `system.file` function. See below

```
> system.file("specs", "ADaM_spec.xlsx", package = "xportr")
[1] "/home/eli.miller/R/x86_64-pc-linux-gnu-library/4.0/xportr/specs/ADaM_spec.xlsx"

**Comment by tataphani** [comment]
Thanks for sharing it I didn’t know that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by esimms999-gsk** [comment]
Perhaps this will help with reading in the spreadsheet ... the metacore package has functions to read in what I think may be the same spreadsheet structure. Once all is read in, a metacore object can be created, but is not necessary if all you want to do is read in the spreadsheet. There are instructions with examples on how to read in the spreadsheet here:

https://atorus-research.github.io/metacore/articles/Building_Specification_Readers.html

A simple example to read in the "Datasets" and "Variables" tabs:

\# Import Review_Aid spreadsheet -------------------------------------------

  doc <- metacore::read_all_sheets(reviewer_aid_path)

 \# Create "ds_spec" df -----------------------------------------------------

  ds_spec <- metacore::spec_type_to_ds_spec(
    doc,
    cols = c(
      dataset = "NAME",
      structure = "STRUCTURE",
      label = "LABEL"
    ),
    sheet = "Datasets"
  )

\# Create "var_spec" df ----------------------------------------------------

  var_spec <- metacore::spec_type_to_var_spec(
    doc,
    cols = c(
      dataset = "DATASET",
      variable = "VARIABLE",
      length = "LENGTH",
      label = "LABEL",
      type = "TYPE",
      format = "SAS_FORMAT"
    ),
    sheet = "Variables"
  )
