### ISSUE TITLE
Export function `xpt_validate`

### ISSUE THREAD

**Issue by ynsec37** [atorus-research/xportr#172]
Dear developer, thank you very much for the developing this wonderful package.

There is one function `xpt_validate`  I want to use.
Could you mind exporting the function `xpt_validate` for easy use? 

https://r-pkgs.org/R-CMD-check.html?q=globalVariables#r-code
> Similarly you are not allowed to use ::: to access non-exported functions from other packages. Either ask the package maintainer to export the function you need, or write your own version of it using exported functions. 

Thank you very much.

**Comment by bms63** [comment]
@atorus-research/xportr-development-team what do you all think of exporting `xpt_validate`.  I think this could be nice addition.

**Comment by vedhav** [comment]
I can see the benefits to exporting it although I don't know why it was not exported in the first place. So my vote would be for exporting it.

@ynsec37 you can still use it with the help of `:::` (so `xportr:::xpt_validate` should work) if you really want to, which is not a good idea in most cases especially if you ship to production as these non-user-facing functions can change without warning or deperication messages by the package maintainers and you won't find documentation for them.
