### ISSUE TITLE
Add `{checkmate}` dependency for function argument checks

### ISSUE THREAD

**Issue by averissimo** [atorus-research/xportr#175]
`xportr` would benefit from some argument checks, first to the exported functions and maybe on a second phase to internal functions

## Why? 

To ensure a proper use of the package and help users/developers avoid problems with usage and development.

## Effort?

I wouldn't expect this would be a very complex change and I'm volunteering for it, if the team thinks it's the right path

#### Example _(function arguments)_

```R
.internal_verbose_choices <- c("none", "warn", "message", "stop")

# ...
xportr_label <- function(.df,
                         metadata = NULL,
                         domain = NULL,
                         verbose = getOption("xportr.label_verbose", "none"),
                         metacore = deprecated()) {
  checkmate::assert_data_frame(.df) # probably this would have to be deferred to after `enexpr` call
  checkmate::assert(
    combine = "or",
    checkmate::check_r6(metadata, "metacore", null.ok = TRUE),
    checkmate::check_data_frame(metadata, null.ok = TRUE)
  )
  checkmate::assert_string(domain, null.ok = TRUE)
  checkmate::assert_choice(verbose, choices = .internal_verbose_choices)
```

#### Example _(small inner changes)_:

https://github.com/atorus-research/xportr/blob/b6af2b1014abf16d03bf958af9d8ec243e2d7091/R/utils-xportr.R#L309

Currently, the if clause would accept a vector of characters as domain (`c("some", "vector", "of", "domains")`) and it would have some unwanted effect.

The change in code would be:

```R
if (checkmate::test_string(domain)) {
```

Some other changes that would be possible are the checks for integerish numbers (for lengths validation) instead of just checking if it's numeric.

**Comment by bms63** [comment]
@averissimo could we add this to our wiki for programming strategy?  it is pretty light, but nice to document somewhere that new features should use this.  

also could we avoid the `::` and add checkmates functions here https://github.com/atorus-research/xportr/blob/main/R/xportr-package.R.  this is just the convention we adopted in xprotr
