### ISSUE TITLE
can't install xportr on kaggle 

### ISSUE THREAD

**Issue by tataphani** [atorus-research/xportr#18]
trying to install xportr on kaggle and it is saying "unknow package from Github" , do you know the reason why

**Comment by bms63** [comment]
What is the code you are running to install onto kaggle?  

Does kaggle access Github repos?

**Comment by tataphani** [comment]
I am not sure , may be that is reason 
I am using this 
install.libraries(devtools) 
devtools::install_github("https://github.com/atorus-research/xportr.git")

**Comment by bms63** [comment]
Should it be 

```
install.packages("devtools")
library(devtools)
devtools::install_github("https://github.com/atorus-research/xportr.git")
```

**Comment by bms63** [comment]
i guess the `devtools::` isn't needed if you run library

**Comment by elimillera** [comment]
Hey @tataphani 
From the remotes::install_github docs:
```
Repository address in the format username/repo[/subdir][@ref\|#pull\|@*release]. Alternatively, you can specify subdir and/or ref using the respective parameters (see below); if both are specified, the values in repo take precedence.
```
Try `devtools::install_github("atorus-research/xportr")`

**Comment by tataphani** [comment]
Even this seems not working , can try on your end ?

**Comment by bms63** [comment]
I can install it.  Maybe comapny firewall or VPN?

although you need a different version of SASXport to get it to work appropriately.  @elimillera maybe we shoudl enhance readme to point to this known issue?

**Comment by tataphani** [comment]
Oh okay , I am planning to move my presentation to rstudio online rather than kaggle , it works there . if you have the solution that would be great if you share with me

**Comment by mstackhouse** [comment]
I think this is a kaggle specific issue. For example, our package Tplyr won't install properly either, and neither will SASxport (which is a dependency of xportr.

Given that this is specific to Kaggle, I'm going to close this out.
