### ISSUE TITLE
Unclear error messaging on xportr_type

### ISSUE THREAD

**Issue by statasaurus** [atorus-research/xportr#19]
When running function I get the following error: 
![image](https://user-images.githubusercontent.com/55274484/153435032-977fc61e-4e22-4d02-aa94-a4c4d2bb851a.png)
It would be nice to know which column this came from so I can fix it. 

The code for the error is [here ](https://github.com/pharmaverse/end_to_end_examples/blob/main/adsl.Rmd)

**Comment by bms63** [comment]
Hey @statasaurus  I think we fixed this.  The code is no longer available that you linked

**Comment by rossfarrugia** [comment]
@bms63 are you sure this is fixed? xportr_type just seems to want to set everything to numeric for me. e.g. see below:

```
> metacore$var_spec %>%
+   print(n=1)
# A tibble: 72 × 6
  variable length label            type      format common
  <chr>     <int> <chr>            <chr>     <chr>  <lgl> 
1 STUDYID       8 Study Identifier character NA     FALSE 
> 
> class(adsltest$STUDYID)
[1] "character"
> 
> test <- metacore$var_spec %>%
+   select(variable, type) %>%
+   mutate(dataset = "ADSL")
> 
> adsltest2 <- adsltest %>%
+   select(STUDYID) %>% 
+   xportr_type(test)
Warning message:
In .f(.x[[1L]], .y[[1L]], ...) : NAs introduced by coercion
> 
> class(adsltest2$STUDYID)
[1] "numeric"
```

**Comment by rossfarrugia** [comment]
@bms63 the fix that @statasaurus made to the end-to-end example worked for me too and i no longer see the above issue 👍
