### ISSUE TITLE
[Question] - Can we reduce the number of exports form xportr?

### ISSUE THREAD

**Issue by vedhav** [atorus-research/xportr#192]
Hello @atorus-research/xportr-development-team 👋 

What are your thoughts on removing the exported functions from xportr that are only intended for internal use: [xportr helper functions](https://atorus-research.github.io/xportr/reference/index.html#xportr-helper-functions)?

I can't think of any users of `xportr` to use these functions and having them in our references sends a false indication that they could be used in some way. So, I recommend we stop exporting them and add `@internal` tag to them.

Additionally, I was surprised where the `adsl` data was coming from after I attached `xportr` and forgot for a while. Will we benefit from exporting it under a different name, like `xportr_adsl` and `xportr_var_spec`?

**Comment by bms63** [comment]
I think it is okay to remove functions from reference tab and use `@internal` - although `xpt_validate` might be nice to have out there still.  perhaps that one can be prettied up a bit.

the renaming of the adsl and var_spec always makes sense to reduce any untoward in peoples environments :)
