### ISSUE TITLE
Summary of Differences for Regulatory Agencies

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#206]
Create a vignette on xportr that lists out differences between the agencies for xpt files.

For example see - https://github.com/atorus-research/xportr/issues/201#issuecomment-1853545157

**Comment by cpiraux** [comment]
Technical conformance guide from regulatory agencies:
- [PMDA](https://www.pmda.go.jp/files/000247157.pdf)
- [NMPA](https://www.nmpa.gov.cn/directory/web/nmpa/images/obbSqc7vwdm0ssrU0enKb7dtd29u9a4tbzUrdTyo6jK1NDQo6mhty5wZGY=.pdf)
- [FDA](https://www.fda.gov/media/153632/download)

Summary by agencies:

|                            |     XPT                                                                                                                                                                                                                                                                                                                                            |     FDA                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     PMDA                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |     NMPA                                                                                                                                                                                                                                                                                          |
|----------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|     File name character    |     The first character must be an English letter   (A, B, C, . . ., Z) or underscore (_). Subsequent characters can be letters,   numeric digits (0, 1, . . ., 9), or underscores   <br><br>  You can use uppercase or lowercase   letters.  <br><br>  Blanks cannot appear in SAS names.  <br><br>  Special characters, except for the underscore, are not   allowed.    |     Dataset in the   transport file should be named the same as the transport file. <br><br>     Variable names,   as well as variable and dataset labels should include American Standard Code  for Information Interchange (ASCII) text codes only.<br><br>      Dataset names should contain only   lowercase letters, numbers, and must start with a letter.                                                                                                                  |     The file name and the dataset name   must be the same for the SDTM and ADaM datasets <br><br>  The Japanese dataset and   alphanumeric dataset must be identical in structure, except for the data   lengths of the Japanese items and the corresponding alphanumeric character   sequence                                                                                                                                                                                      |     ?                                                                                                                                                                                                                                                                                             |
|     File name length       |     maximum length of 8 bytes                                                                                                                                                                                                                                                                                                                      |     8 characters                                                                                                                                                                                                                                                                                                                                                                                                                                                      |     -                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     ?                                                                                                                                                                                                                                                                                             |
|     Variable name          |     The name can contain letters of   the Latin alphabet, numerals, or underscores.  <br><br>  The name cannot contain blanks or special characters except for the   underscore. <br><br>   The name must begin with a letter of the Latin alphabet (A–Z, a–z) or the   underscore.                                                                                |     Variable names,   as well as variable and dataset labels should include American Standard Code   for Information Interchange (ASCII) text codes only.   <br><br>        Variable names should contain only   uppercase letters, numbers, and must start with a letter                                                                                                                                                                                                     |     The Japanese dataset and   alphanumeric dataset must be identical in structure, except for the data   lengths of the Japanese items and the corresponding alphanumeric character   sequence                                                                                                                                                                                                                                                                                     |     ?                                                                                                                                                                                                                                                                                             |
|     Variable length        |     8 bytes                                                                                                                                                                                                                                                                                                                                        |     8 characters                                                                                                                                                                                                                                                                                                                                                                                                                                                      |     -                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     ?                                                                                                                                                                                                                                                                                             |
|     Label character        |     -                                                                                                                                                                                                                                                                                                                                              |     Variable names, as well as variable and dataset labels should include   American Standard Code for Information Interchange (ASCII) text codes only.   <br><br> Do not submit study data with the following special characters in variable   and dataset labels:   <br><br>   1. Unbalanced apostrophe, e.g., “Parkinson's”   <br><br>   2. Unbalanced single and double quotation marks   <br><br>   3. Unbalanced parentheses, braces or brackets, e.g.,‘(‘, ‘{‘and ‘[‘                          |     The Japanese dataset and   alphanumeric dataset must be identical in structure, except for the data   lengths of the Japanese items and the corresponding alphanumeric character   sequence                                                                                                                                                                                                                                                                                     |     For eSubmission in   China, one of the requirements is to translate the foreign language data   package (e.g., English) to Chinese. Variable labels, dataset labels, MedDRA,   WHO Drug terms, primary endpoint-related code lists, etc., need to be   translated from English to Chinese.    |
|     Label length           |     40 bytes                                                                                                                                                                                                                                                                                                                                       |     40 characters                                                                                                                                                                                                                                                                                                                                                                                                                                                     |     -                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     ?                                                                                                                                                                                                                                                                                             |
|     Values character       |     -                                                                                                                                                                                                                                                                                                                                              |     Variable values   are the most broadly compatible with software and operating systems when they   are restricted to ASCII text codes (printable values below 128). Use UTF-8   for extending character sets; however, the use of extended mappings is not   recommended. Transcoding errors, variable length errors, and lack of software   support for multi byte UTF-8 encodings can result in incorrect character   display and variable value truncations.    |     If variables had been collected in   Japanese and there is a risk of losing certain information by translating it   into English, the descriptions in Japanese are necessary and appropriate, and   data written in Japanese (hereinafter referred to as Japanese data) may be   submitted.           In the Japanese dataset, only the   Japanese items should be Japanese and the rest should be alphanumeric(=ASCII)   data, similar to that in the alphanumeric dataset.    |     For eSubmission in   China, one of the requirements is to translate the foreign language data   package (e.g., English) to Chinese. Variable labels, dataset labels, MedDRA,   WHO Drug terms, primary endpoint-related code lists, etc., need to be   translated from English to Chinese.    |
|     Values length          |     200 bytes                                                                                                                                                                                                                                                                                                                                      |     The allotted   length for each column containing character (text) data should be set to the   maximum length of the variable used across all datasets in the study except   for suppqual datasets.                                                                                                                                                                                                                                                                |     -                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     ?                                                                                                                                                                                                                                                                                             |
|     Format                 |     SAS format                                                                                                                                                                                                                                                                                                                                     |     SAS format                                                                                                                                                                                                                                                                                                                                                                                                                                                        |     -                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     ?                                                                                                                                                                                                                                                                                             |
|     Type                   |     Numeric and character                                                                                                                                                                                                                                                                                                                          |     -                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |     -                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |     -                                                                                                                                                                                                                                                                                             |
|     File size              |     -                                                                                                                                                                                                                                                                                                                                              |     5 GB                                                                                                                                                                                                                                                                                                                                                                                                                                                              |     To be consulted if sponsors have   datasets >= 5 GB     No requirement to split datasets                                                                                                                                                                                                                                                                                                                                                                                        |     ?                                                                                                                                                                                                                                                                                             |

**Comment by bms63** [comment]
@atorus-research/xportr-development-team This is a really good summary of the differences between the agencies!

Definitely a mini-vignette for this one.  For some of the ? sections, I bet when we put it out there we will get some feedback on them!
