### ISSUE TITLE
xportr_length: Set ---DTC variables length to maximum length based Date (10) or Date/Time (19)

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#207]
Update to `xportr_length()` that sets DTC variables to maximum length based on Date (10) or Date/Time (19) inputs.  

Add a check/warning when the spec length is populated for the --DTC variables as the define.xml should not have a length (missing).

**Comment by cpiraux** [comment]
Reopen the issue as it is not yet implemented. To much issues with DTC variables :sweat_smile:
