### ISSUE TITLE
Add `xportr()` to deep dive vignette

### ISSUE THREAD

**Issue by EeethB** [atorus-research/xportr#215]

**Comment by bms63** [comment]
Apologies @kaz462 this is the one that needs some love!!!

**Comment by kaz462** [comment]
which function should be added? btw, the [deep dive vignette](https://atorus-research.github.io/xportr/articles/deepdive.html) looks awesome!

**Comment by bms63** [comment]
its the new xportr() that @EeethB created in https://github.com/atorus-research/xportr/pull/200

**Comment by kaz462** [comment]
> its the new xportr() that @EeethB created in #200

thx! it seems the website isn't up-to-date yet? https://atorus-research.github.io/xportr/

**Comment by bms63** [comment]
use the https://atorus-research.github.io/xportr/dev and you should get the dev website.  I think there is a recent PR that failed to build PR but I don't think that would impact reading up on the funciton
