### ISSUE TITLE
Q: Can all or any of the Suggested packages be removed?

### ISSUE THREAD

**Issue by averissimo** [atorus-research/xportr#221]
Thinking about:

- {devtools}
- {lintr}
- {spelling}
- {usethis}
  - only 1 mention on documentation

**Comment by bms63** [comment]
I think some of our workflows makes use of these packages?

![image](https://github.com/atorus-research/xportr/assets/10111024/94a806cd-e667-4b10-b179-95aca7c3fef8)

We could rebuild the workflows and just manually install them in the workflow and remove from the Suggest.  WDYT?

**Comment by averissimo** [comment]
Yes, I think that would be a nice solution.
