### ISSUE TITLE
Cleanup of test code

### ISSUE THREAD

**Issue by EeethB** [atorus-research/xportr#223]
We have really strong test coverage, but the tests have gotten a little messy in places. I think there's some cleanup we can do.

https://github.com/atorus-research/xportr/pull/200#discussion_r1461830031

https://github.com/atorus-research/xportr/pull/200#discussion_r1461816354

Please add links to other comments as needed for specific issues noticed!

**Comment by EeethB** [comment]
https://github.com/atorus-research/xportr/pull/200#discussion_r1461841230

**Comment by averissimo** [comment]
One more :-)

```r
diff --git a/R/metadata.R b/R/metadata.R
index bf24ecd..645acc4 100644
--- a/R/metadata.R
+++ b/R/metadata.R
@@ -32,14 +32,12 @@
 #'
 #' xportr_metadata(adlb, metadata, "test")
 #'
-#' if (rlang::is_installed("magrittr")) {
-#'   library(magrittr)
-#'
-#'   adlb %>%
-#'     xportr_metadata(metadata, "test") %>%
-#'     xportr_type() %>%
-#'     xportr_order()
-#' }
+#' library(magrittr)
+#'
+#' adlb %>%
+#'   xportr_metadata(metadata, "test") %>%
+#'   xportr_type() %>%
+#'   xportr_order()
```

**Comment by bms63** [comment]
- [ ] Look into suppresswarnings
- [ ] Organization of the test code (bonus-time)
- [ ] Subject headings for test - what is it testing and is it described in a nice and clear way 

Cross-check with what Andre is doing here: #219
