### ISSUE TITLE
pkgdown site fail (adsl_admiral no longer available)

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#237]
I believe we have our own adsl dataset available and the example should make use of it.

I believe if we remove this from adsl from admiral, then admiral can be removed from Suggests.  

When the pkgdown action builds it can't find this object any longer...can someone look into this please? @atorus-research/xportr-development-team 

![image](https://github.com/atorus-research/xportr/assets/10111024/34633cb4-f864-430d-b871-9a5032508ecb)

# Definition of Done

- [ ] Remove admiral_adsl from examples
- [ ] Update examples to use xportr adsl
- [ ] Remove admiral from Suggests
- [ ] Make sure site can rebuild.

**Comment by averissimo** [comment]
The site builds and deployes :tada:

https://atorus-research.github.io/xportr/dev/reference/index.html
