### ISSUE TITLE
Tidyverse might have some deprecation that may impact some `xportr` functions

### ISSUE THREAD

**Issue by sadchla-codes** [atorus-research/xportr#247]
<img width="639" alt="Screenshot 2024-02-21 at 10 46 18 PM" src="https://github.com/atorus-research/xportr/assets/112789549/ab459072-1ddd-4965-aef6-1f8453b8e788">

It's causing the 2  warnings when running tests from `xportr::xportr_length()`
<img width="333" alt="Screenshot 2024-02-21 at 11 08 29 PM" src="https://github.com/atorus-research/xportr/assets/112789549/ee0ba6a3-ad9c-4b22-b5c6-a9d611338ede">

<img width="605" alt="Screenshot 2024-02-21 at 11 11 56 PM" src="https://github.com/atorus-research/xportr/assets/112789549/367a7884-c99e-46ee-8e7e-43bc25b5c141">

**Comment by bms63** [comment]
Interesting this is just now showing up.  @atorus-research/xportr-development-team anyone have some bandwidth to help knock this one out!  I'm a bit full-up at the moment! 😭

**Comment by vedhav** [comment]
Looks like a quick fix. I just sent a small PR for this.
