### ISSUE TITLE
xportr_label to list out variables missing labels

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#258]
![image](https://github.com/atorus-research/xportr/assets/10111024/2f252831-a9b3-4f7b-9aef-c3bbaacf23d1)

**Comment by elimillera** [comment]
I think this can be closed as well:
 adsl <- data.frame(
   USUBJID2 = c(1001, 1002, 1003),
   SITEID = c(001, 002, 003),
   AGE = c(63, 35, 27),
   SEX = c("M", "F", "M")
 )

 metadata <- data.frame(
   dataset = "adsl",
   variable = c("USUBJID", "SITEID", "AGE", "SEX"),
   label = c("Unique Subject Identifier", "Study Site Identifier", "Age", "Sex")
 )

 adsl <- xportr_label(adsl, metadata, domain = "adsl", verbose = "warn")
 ── Variable labels missing from metadata. ──

✔ 1 labels skipped
Warning message:
Variable(s) present in dataframe but doesn't exist in `metadata`.
✖ Problem with `USUBJID2`
