### ISSUE TITLE
Bug: Homepage installation instruction update

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#263]
### What happened?

![image](https://github.com/atorus-research/xportr/assets/82581364/c6b1dab0-a0a6-43af-872a-2418eb68585c)

Your `devel` branch no longer exists - update above to rely on `main` now.

**Comment by elimillera** [comment]
Hey @rossfarrugia, Where is this in the docs? I'm not seeing it in the read me or the Get Started page in the pkgdown.

**Comment by rossfarrugia** [comment]
@elimillera looks like already fixed in the upcoming release: https://github.com/atorus-research/xportr#development-version
