### ISSUE TITLE
Feature Request: `xportr_write()` file size warning should be flexible

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#267]
### Feature Idea

@bms63 @elimillera  - @bundfussr noticed `xportr_write()` issues a warning if the size is greater than 5GB (without an option to adjust the threshold). We heard from our eSub team that Japan (PMDA) allows 10GB so wondering if this should be an argument user could provide. I have a similar connected idea on `xportr_split()` but will make a separate issue.

**Comment by elimillera** [comment]
Closed by https://github.com/atorus-research/xportr/pull/272
