### ISSUE TITLE
Feature Request: `xportr_split()` enhancement for easier user experience

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#268]
### Feature Idea

@bms63 @elimillera  - i chatted with our esub team here further about the split datasets (and showed them the new `xportr_split()` function). they had 2 pieces of feedback to enhance this function:

- users currently either have to manually work out if this is needed or check the warning from `xportr_write()` which is not flexible enough (see https://github.com/atorus-research/xportr/issues/267 - as China limit is 4GB and Japan is 10GB for example). their advice here was to have one option somewhere (e.g. in `xportr_write()` where you set the limit as an argument and then it automatically does the split according to some default split rule according to the threshold you provide).

- for the split rules they said doing this by a variable (e.g. `LBCAT`) is impractical as it would end up with a large number of split datasets and you'd have to explain in reviewer's guide exactly how you choose to split each dataset. the convention they usually use instead is to just split by records according to the sort order of the dataset (with as many as possible records being included in split 1 up until the threshold the user provides). then in the reviewers guide you just give one simple sentence to explain how this is done for every dataset where needed.

p.s. something that was news to me... they said that actually they always send via esub both the full oversize datasets and the split datasets bizarrely, and the HA then can just choose either to set them together or use the full datasets provided anyway. makes you wonder why this is even needed in the first place! 

FYI @bundfussr

### Reproducible Example/Pseudo Code

Here's an example of how this could look in future:

`xportr_write(sizelimit=4)`

And within this function have code to check if _sizelimit_ not NULL then apply `xportr_split()`

But default of `xportr_split()` here would be to use the _sizelimit_ user provides and split by records, not by _split_by_

i.e. in this case include the maximum number of records possible in the split 1 dataset up to <=4GB file size

**Comment by adchan11** [comment]
Hi @bms63 @elimillera , I am helping Ross from Roche's side to take on this feature request. If I have any questions, I'll post here. Thanks.

**Comment by bms63** [comment]
Hi @adchan11 sounds great!!  I don't think we have any plans for a release - so when you are done we will release an updated package.

@atorus-research/xportr-development-team anything you might want to add to a mini-release?

**Comment by elimillera** [comment]
I don't have bandwidth for dev at the moment so happy to push a release when any updates are ready.
