### ISSUE TITLE
Add extra character type

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#47]
@bms63 xportr seems to expect "character" or "Char" for type (see https://github.com/atorus-research/xportr/blob/main/R/zzz.R), whereas Roche specs use "text" here. Can this be added to the acceptable list of `character_types`?

We weren't sure if any other knock-on impacts of this across metacore/metatools so please do shout if you see any concerns, but it would save us updating our global standards or temporarily updating and causing confusion for users. Plus sure other companies will have same.

**Comment by mstackhouse** [comment]
@rossfarrugia  is this closed from your side?

**Comment by rossfarrugia** [comment]
yes, thanks @mstackhouse
