### ISSUE TITLE
Wordsmith

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#5]
![image](https://user-images.githubusercontent.com/10111024/130472280-f9cd0997-0012-4076-8837-742b3ea76d61.png)

**Comment by bms63** [comment]
Maybe **_This package is being jointly developed by GSK and Atorus._**

**Comment by mstackhouse** [comment]
@bms63 I gave you write access to this repo. You can go ahead and PR these typos if you'd like :)
