### ISSUE TITLE
xportr_format issue from Roche testing

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#60]
@bms63 our testers keep seeing from `xportr_format` the following:
Error: Writing failure: A provided format string could not be understood.

Yet here's the only values being supplied for formats which seem OK to me:
```
unique(metacore$var_spec$format)
[1] NA            "date9."      "datetime20."
```

Have you seen this one before? Any tips?

**Comment by bms63** [comment]
@elimillera do you have bandwidth?

**Comment by adchan11** [comment]
Hello, this issue continues to persist:
![image](https://user-images.githubusercontent.com/82629083/217390263-83e34990-6e21-46ca-b92a-bc2cd874fa41.png)

I'm using the latest package version:
> packageVersion('xportr')
[1] ‘0.2.0’

Even though my dataset passes the validation checks, it still gets the error at the write_xpt line from haven:
![image](https://user-images.githubusercontent.com/82629083/217390445-0d99c199-8833-4e12-b2b2-59cffb951292.png)

**Comment by zdz2101** [comment]
@adchan11 Are you seeing the error after running `xportr_write()` ? Or is it still happening after `xportr_format()`

**Comment by adchan11** [comment]
@zdz2101 this is after running all these functions. It only happens after xportr_write. xportr_format runs fine
![image](https://user-images.githubusercontent.com/82629083/217671822-a32cd8f3-f673-431b-a702-507e36439711.png)
