### ISSUE TITLE
xportr_type question and request from Roche testers

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#61]
@bms63 sorry but one request ishould have included before in https://github.com/atorus-research/xportr/issues/47 but can we also include "Integer" as a valid numeric type from the specs? Roche uses this as standard for some reason - I guess because they wanted to keep some level of language agnosticism in the specs.

Also a question: what would you be expecting the specs to say here for type for DTC, DT, and DTM variables respectively? I used Character, Date, and POSIXct respectively in testing to match the R class equivalents, but guessing as the ultimate aim is XPT here then we'd use character, numeric and numeric. Although when I do that I get:
```
Error in `xportr_logger()`:
Variable type(s) in dataframe don't match metadata:
```

I think having some more date cases in the examples in the xportr documentation would really help both around `xportr_type` and `xportr_format`.

**Comment by bms63** [comment]
@elimillera do you have bandwidth?

**Comment by elimillera** [comment]
Hey @bms63 I have some time this weekend. I'll try to crank this out

**Comment by rossfarrugia** [comment]
@elimillera how's things going with this and https://github.com/atorus-research/xportr/issues/60? we're getting next batch of new teams exploring xportr in the coming months here and would be great to have these pieces resolved so they don't get put off these packages due to such console messages.

**Comment by oreillb1** [comment]
If possible please may we have a more informative error message created  than "Error: Writing failure: A provided format string could not be understood." It would greatly help troubleshooting to know which column(s) had an incorrect format(s) assigned.
Having set formats of NA, DATE9. or DATETIME20.  in my ADSL specs according to https://atorus-research.github.io/xportr/reference/xportr_format.html#examples there are some gaps in my understanding which formats should be assigned to various column types and some more examples would be helpful. 
I assumed that columns like [DM.ARM], [DM.DMDY], [DM.DMDTC] should be assigned  "NA" , and derived columns like [ADSL.RANDDT] should be assigned DATE9. but unsure what format(s) need changing when the current error is produced..

**Comment by elimillera** [comment]
Hey @rossfarrugia, I've updated some of the default character formats in #66. Based on the specs I see for xpt the following should be 'Char' values in xpt:
`c("character", "Char", "text", "Date", "POSIXct",  "POSIXt", "date9.", "datetime20.")`
This can be overridden if you have custom class names but let me know if theres anything else you could see as a default. You can update the value of the option `xportr.character_types` if there's anything you want to test in the meantime. Take a look at the screenshot in #65 for the reference I'm using for coercing dates to character.

Anything that's not noted as a character value will be coerced to a numeric type.

I'll add improvements to the `xportr_format` and `xportr_type` documentation to our backlog for 1.0.0 as well.

To your question of including "Integer" as a numeric type, anything that isn't in the xportr.character_types vector will be treated as numeric.

**Comment by rossfarrugia** [comment]
Thanks Eli! i think its the date/datetimes that are causing us the most issues on our side as in our Roche specs we refer to them as Integer with a format applied, as technically in SAS dates are stored as a number (e.g. for datetime the integer equals the number of seconds from January 1,1960). But when they get formatted they do appear with characters of course. I guess what you're saying here is we should refer to them as character now in our specs and then `xportr_logger` shouldn't give us these errors. More examples in the documentation would definitely help! Appreciate the support.
