### ISSUE TITLE
read_sas_lib function

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#62]
function (libname = ".", data, lower_names = FALSE) 
{
    sasFile <- paste0(substitute(data), ".sas7bdat")
    filePath <- file.path(libname, sasFile)
    if (file.exists(filePath)) {
        out_df <- haven::read_sas(filePath)
    }
    else {
        stop("Cannot find file, check spelling and case")
    }
    if (lower_names) {
        out_df <- out_df %>% rename_all(tolower)
    }
    out_df
}

**Comment by elimillera** [comment]
Hey @bms63, Is this functionality you want to be added into xportr?

**Comment by bms63** [comment]
yeah ... since we already use `haven`.  Just less typing when loading sas datasets.
