### ISSUE TITLE
xportr NA strategy?

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#63]
@bms63 what's the {xportr} strategy around NA values? We were wondering if {xportr} might essentially do the opposite of {admiral} `convert_blanks_to_na()` and put R's NA values back to a more SAS expectant blank for the xpt files, but doesn't seem to be the case.  

It came up as some of our testers are getting warnings:
`Column `xxx` contains string values longer than user width 1. Width set to 2 to accommodate. `

It looks to be down to NA values from the {admiral} functions. We could set the widths to 2 of course in our define and maybe FDA would expect to see NAs given we'd have notified already that we're using R to create the xpt, but just wondering if this ever came up in xportr team discussions before?

**Comment by bms63** [comment]
Hey Ross.  I'm not sure we had much of a strategy.  I will try to get back to this package in mid-December, but I'm struggling with Study Work and commitments on admiral.  

Unfortunately, GSK doesn't have much of a resource strategy for working on this.... when Eli and I got this to CRAN I just did this work on the weekends off the clock, which I think Eli did as well.

Anyways, @mstackhouse, @elimillera, @rossfarrugia, maybe  we could discuss long-term strategy and resourcing of this package if it is going to become a critical part of the pipeline.  I can try and discuss with Michael Rimler and others at GSK to get a resource onto this project or at least green light as something I can work on.

I don't think we have a ton of work to do here.  Just some tweaks and a better cycle on feedback from users as it comes in.  Just need the time!!

**Comment by rossfarrugia** [comment]
Thanks Ben! Appreciate if you could discuss with Michael and co to see if some form of maintenance resourcing strategy could be worked out for this one. Agree the issues are not major.

**Comment by thomas-neitmann** [comment]
We are planning to use {xportr} in the R Submission Pilot 3 for AdaM datasets. I feel like this is an important issue we should solve by the time we submit the pilot packages (early next year). From m ypoint of view the only sensible thing is to automatically convert `NA` values to `""` when xporting.

**Comment by elimillera** [comment]
Hey @thomas-neitmann and @rossfarrugia, one of the ideas we had for xportr was to only do operations on columns. IMO converting any actual values would be done before xportr enters the pipeline. I would say that admiral would actually be a more appropriate package to include functionality that modifies data. I think it could be included in a helper function in xportr as well if you think its a critical piece missing from the pipeline.

**Comment by mstackhouse** [comment]
@thomas-neitmann I would agree that this is better placed in admiral, because I don't think we should blindly replace NAs. {xportr} is focused on metadata and writing to XPT. The line in the sand we wanted to draw was that it doesn't modify the vectors. That's why it also doesn't do any row sorting. The user should themselves say "I'm deciding to convert NA to "".

**Comment by mstackhouse** [comment]
Or maybe metatools? @statasaurus do you think `convert_blanks_to_na()` and `convert_na_to_blanks()` would be valid functions for metatools?

**Comment by rossfarrugia** [comment]
@elimillera @mstackhouse that makes sense to me! we already have https://pharmaverse.github.io/admiral/reference/convert_blanks_to_na.html as Mike points out in {admiral} so we'd just need the reverse `convert_na_to_blanks()` and we could add this in http://examples.pharmaverse.org/data/adsl/ before the {xportr} steps.

@bms63 & @thomas-neitmann do you agree?

**Comment by statasaurus** [comment]
Yeah I think it makes sense to dump into metatools. I am happy to add them for the next release if people are happy to move it out of admiral

**Comment by bms63** [comment]
@rossfarrugia did we want to keep these in `admiral` still?  Or are we developing `convert_na_to_blanks()` in `admiral` and then once that is done moving both to `metatools`?  I am fine either way.

**Comment by rossfarrugia** [comment]
I'd keep them both in `admiral` as neither are driven by metadata as such, we'll cover `convert_na_to_blanks()` there with one of our devs. We just agreed to add the function so issue incoming and we'll squeeze it in next release.

**Comment by statasaurus** [comment]
But won't this also be an issue when making SDTMs?

**Comment by bms63** [comment]
> But won't this also be an issue when making SDTMs?

That is good point.  I think Ross wants this function for Roche templates ASAP and we are releasing updates on December 5th so would be available for their developers much sooner.  But long-term moving to `metatools` makes more sense to me so programmers can do the same thing with their SDTM data.

**Comment by rossfarrugia** [comment]
Let's put it in `admiral` for now and chat at a future monthly call on this. I don't feel personally that's the only criteria for this decision, as otherwise you'd put anything related to study days, baseline flags, etc all in metatools too given they're in SDTM as well. I'll check with our `roak` SDTM package devs how they achieve such things as that'll be open sourcing next year.

**Comment by statasaurus** [comment]
Oh I don't love {metatools} for this. I just want to make the there isn't too much scope creep

**Comment by rossfarrugia** [comment]
Yes agree. It could become a dumping ground for many things otherwise. Better to keep it focused on things driven by metadata.

**Comment by statasaurus** [comment]
But, does putting it in admiral just shift the scope of admiral?

**Comment by rossfarrugia** [comment]
I'm OK with that. We're debating a 1 line `if_else()` here, not a massive effort.

**Comment by rossfarrugia** [comment]
Function available in latest admiral release so will close this issue now as no longer an issue.

**Comment by bundfussr** [comment]
The issue was fixed in haven (https://github.com/tidyverse/haven/issues/699).
