### ISSUE TITLE
xportr_type needs to accept 'text' as a type option 

### ISSUE THREAD

**Issue by statasaurus** [atorus-research/xportr#65]
According to the define.xml definition these are the valid data types 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/55274484/197984222-7ed39791-1cf3-4de8-bc20-1996c57569e9.png">
But, when you have 'text' as a variable type `xportr_type` will convert it to character. 

Also consider a warning if the type is unknown, and maybe default to character rather than to numeric

**Comment by mstackhouse** [comment]
@statasaurus so according to the table above, "text" should be entered into the SAS V5 Xport file as Char type. The second column is the valid type in the XPT file. So what's exactly the issue that's happening here? In our convo, you mention that we go NAs, but can you provide a reprex showing the actual issue?

**Comment by statasaurus** [comment]
What is in the spec is in the left most column. So the type column for the value_spec says "text"

**Comment by elimillera** [comment]
Hey @statasaurus, `xportr` maps the following types to char: "character", "Char", and "text". Everything else is coerced to numeric. I think a good enhancement could be to update the default list to include:
- Date
- POSIXct
- POSIXt

If you have any other things you think should be coerced to char by default let me know.

**Comment by statasaurus** [comment]
So we had text in the metacore object and it was still causing issues where things were coming out NA. I think at the very least there should be an warning when things are being converted to NA

**Comment by elimillera** [comment]
This should be resolved in xportr 0.2.0. NA values are handled a bit more gracefully. `xportr_type` is a little weird and I'm wondering if theres a better way to communicate what its doing under the hood.

**Comment by elimillera** [comment]
@statasaurus Can you give this a try in the 'type_updates' branch? I think I have this actually figured out now. SITEID is the only variable thats getting updated now.
