### ISSUE TITLE
devel and main branch seem out of sync

### ISSUE THREAD

**Issue by rossfarrugia** [atorus-research/xportr#68]
@elimillera @bms63  Something looks off with your last release as DESCRIPTION file shows 0.2.0 in `main` but `devel` still 0.1.0 as FYI. 

So people have issues if using: 
`install_github("atorus-research/xportr", ref = "devel")`

**Comment by mstackhouse** [comment]
We need branch controls set up on the repo - it looks like !67 was merged directly to main.

**Comment by elimillera** [comment]
This has been fixed, devel will be ahead of main from now on. Thanks @rossfarrugia!
