### ISSUE TITLE
xportr_write error in valid format

### ISSUE THREAD

**Issue by adchan11** [atorus-research/xportr#69]
Hi @bms63 

This is in the context for using these functions for Roche. I'm getting an error in the xportr_write step of my code:
![image](https://user-images.githubusercontent.com/82629083/216421974-4c63b2b5-10c1-4a57-8f8a-016a4b1c0fbc.png)
 I dug deeper into the code and when it calls xpt_validate, there's an issue with the format assigned:
![image](https://user-images.githubusercontent.com/82629083/216422127-c4d92792-d37e-43cd-a420-322a51789884.png)

can the expected_formats be updated with permutations of timew?

**Comment by bms63** [comment]
Thanks! @adchan11 I will look into this issue.

**Comment by bms63** [comment]
@adchan11 FYI @zdz2101  has made this update.  Please let us know if this fix works for you

**Comment by adchan11** [comment]
Hi @bms63 

I get this error when running xportr_write (I also get an error at xportr_type but that's a separate issue I created in the issues tab so I commented it out of this code):
![image](https://user-images.githubusercontent.com/82629083/218890859-b94cfc74-4c75-4573-a9c3-3c8a5a780594.png)

I took a look at the formats of my adsl dataframe and it looks like time5 was not applied by the xportr_format function: 
![image](https://user-images.githubusercontent.com/82629083/218890979-004feb1a-b7f3-4a56-b34b-ac6bf45fb249.png)

These are the unique formats in my dataframe:
![image](https://user-images.githubusercontent.com/82629083/218891060-aa599e78-4897-4b53-823c-f320ecff0319.png)

Is it because there is a NULL format present that xportr_write is recognizing as not a proper format?

**Comment by bms63** [comment]
Hi @adchan11 is this using the development version?  @zdz2101 FYI

@elimillera lets pause on sending to CRAN until we can see if @adchan11 issue is fixed with out devel version

**Comment by zdz2101** [comment]
@adchan11 you might need to call:
`remotes::install_github("atorus-research/xportr", ref = "devel")`
 if you didn't already

**Comment by adchan11** [comment]
Hi @bms63 @zdz2101 
I can confirm I used the latest development version using the ref = 'devel' and still get this error:
![image](https://user-images.githubusercontent.com/82629083/219233623-b3e36396-996a-469a-b78e-7ebb9662d8f0.png)
