### ISSUE TITLE
Better documentation for metadata requirements/expectations 

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#7]
![image](https://user-images.githubusercontent.com/10111024/140823741-cda84724-e56f-4ff1-860d-ffbeaebeb73e.png)

**Comment by bms63** [comment]
Allow users to develop a spec file that can be used in P21 uploade

**Comment by elimillera** [comment]
Add documentation to how df metadata is read/needed with options

**Comment by elimillera** [comment]
Get rid of options for 'verbose'. Just use character vector/function

**Comment by cpiraux** [comment]
Idea: Consider changing the argument name 'verbose' to 'message_severity'

**Comment by bms63** [comment]
I like `message_severity`

**Comment by EeethB** [comment]
I think this comment might be better tied in here: https://github.com/atorus-research/xportr/pull/107#discussion_r1193767624
