### ISSUE TITLE
xportr_type - variable types do not match metadata

### ISSUE THREAD

**Issue by adchan11** [atorus-research/xportr#73]
Hi @bms63 

I wanted to create a separate issue for xportr_type I'm getting. It says the variable types don't match my metadata but when I compare the type in my metacore object and the class of my dataframe, they are the same (i.e. 'Date')
![image](https://user-images.githubusercontent.com/82629083/219235834-39b04cec-f144-4362-9689-c4a403334d69.png)

![image](https://user-images.githubusercontent.com/82629083/219235909-e50dc825-1314-4e82-83b1-0970db4516da.png)

It seems like all my --DT (date) and --DTM (datetime) variables are being flagged by xportr_type.

**Comment by adchan11** [comment]
Hi @bms63 , just wanted to follow up on this issue, thanks!

**Comment by elimillera** [comment]
@adchan11 
`xportr_type` does something a little weird here. Theres no concept of a "Date" type in xpt, its either character or numeric. Here xportr is finding anything that should collapse into character and doing that. If you convert those into 'character' this should be resolved.
