### ISSUE TITLE
Add option to print warning instead of error for validation failures in `xportr::xportr_write()`

### ISSUE THREAD

**Issue by ddsjoberg** [atorus-research/xportr#78]
Congratulations on the v0.2.0 release!

The validation checks in `xportr::xportr_write()` are awesome! Can we have an argument to change this error to a warning/message instead of a warning? Sometimes I know there are a few things to resolve, but just need to save the file and move on ;)

Thank you!
```
Error in `xportr::xportr_write()`:
! The following validation failed:
```

**Comment by bms63** [comment]
Hi @ddsjoberg.  Thank you!  

We were going to get a working group together at the end of March to really get `xportr` into production ready-state.  Right now it feels a bit flimsy and unfinished.  Is it possible to include you on the invite.   I'm hoping to have a lot of hands on deck to help push this package into the next level!

**Comment by ddsjoberg** [comment]
Hey hey @bms63 ! Happy to join!

**Comment by ddsjoberg** [comment]
I think if this line was updated from `rlang::abort()` to `rlang::warn()` that would be perfect.

https://github.com/atorus-research/xportr/blob/cd4da91e9e05e5d846567bdeb6fdad43a8b61fec/R/write.R#L50

Users will still be notified of any non-compliant names, and retain the option to force an error by setting `option(warn = 2)`

**Comment by bms63** [comment]
Hi @ddsjoberg please check out the PR #105.  Feedback appreciated!
