### ISSUE TITLE
Make a release for v0.1.0?

### ISSUE THREAD

**Issue by ddsjoberg** [atorus-research/xportr#79]
It's often helpful to refer to a GH repo's release using the typical syntax like, `"atorus-research/xportr@v0.1.0"`. If you find the commit associated with the release, you can make a release from the that point in the repo's history. Thank you! ❤️

**Comment by elimillera** [comment]
Hey @ddsjoberg. Looks like we missed that on that release. That has been added. Thanks!

**Comment by ddsjoberg** [comment]
Awesome, thank you @elimillera !!

I see that the tag was created. You can also link the tag to a new GH release. While not required, this is what is typically done. Up to you!

**Comment by elimillera** [comment]
You bet. Added the release as well
