### ISSUE TITLE
More Documentation to explain how xportr functions work

### ISSUE THREAD

**Issue by adchan11** [atorus-research/xportr#81]
Hello,

As alluded to from #61 , #73 , and #69 , we realized there is some challenges in understanding how the functions work in order to troubleshoot the errors we've been getting. We spent a lot of time to read the code line by line in the functions but it would be more efficient to improve the documentation so that future users don't need to do this. I see there is a vignette: 

https://github.com/atorus-research/xportr/blob/main/vignettes/xportr.Rmd

but I don't think it's enough to explain how the xportr functions work. 

This is an example of the kind of documentation that would be helpful (how I explain the xportr_type function):

![image](https://user-images.githubusercontent.com/82629083/224761471-da27bf03-7467-4115-be38-57c62deda093.png)
![image](https://user-images.githubusercontent.com/82629083/224761534-024bf8e8-d138-4901-a5c5-f67c25f4bbd8.png)
![image](https://user-images.githubusercontent.com/82629083/224761609-baaecd70-abcc-40d6-a24f-b8534237e183.png)
![image](https://user-images.githubusercontent.com/82629083/224761683-e5b0ba3c-9a4d-45e3-8bfb-894f1138f842.png)
![image](https://user-images.githubusercontent.com/82629083/224762011-1f27d316-9ad7-4df3-bc5f-0aa438d908c6.png)

**Comment by bms63** [comment]
Thanks @adchan11.  We are going to re-group at the end of March with a proper team and bring `xportr` to production-readiness.  

`xportr` is one of those packages that is not very exciting to people - it is not tables, interactive dashboard or ADaMs, but just deals with the bottleneck of our industry xpt files!  I think I have gather enough people that the workload will be doable for us to bring up the functions to the necessary level of readiness, build out better documentation and increase our unit testing capabilities.  

Do you have the bandwidth to assist us?

**Comment by adchan11** [comment]
Sounds good, I can assist!

**Comment by cpiraux** [comment]
In the documentation, we can see an issue with xportr_type(). I have the impression that types from ADaM_admiral_spec.xlsx: Char, Num are not handled by the function. I follow the documentation and get this message:


![Image](https://user-images.githubusercontent.com/69685640/233410073-62539fdf-4ed0-4393-807d-4423dbdaa966.png)

It is not clear that Char and Num are not correct type values.
All variables are coerce to dbl:


![Image](https://user-images.githubusercontent.com/69685640/233410177-b59299a9-1222-4f6a-8017-56dbba361703.png)

**Comment by elimillera** [comment]
Initial work is here: https://github.com/atorus-research/xportr/compare/main...issue_81_documentation

**Comment by vedhav** [comment]
Thanks @adchan11 for the issue and PR. The `deepdive.Rmd` vignette that was built as part of the 0.3 version release does a good job of explaining how the `xportr_*` functions along with the verbose options that can be customized.
I've added a small PR making some changes to it, and that PR will close this issue. But, feel free to open a new issue if you feel that we can benefit from documenting something else.

**Comment by adchan11** [comment]
Thank you! @vedhav
