### ISSUE TITLE
Documentation: Example for ziping up xpts in CDISCish format

### ISSUE THREAD

**Issue by bms63** [atorus-research/xportr#9]
Uploading to P21 must be in a zip file.  Can we take out this step for the user?

**Comment by elimillera** [comment]
This looks to be very straight-forward in R. {utils} is a base package and has a zip function to do this.

**Comment by elimillera** [comment]
`xportr_zip` to zip up a set of datasets?

**Comment by cpiraux** [comment]
If the zip file is used to facilitate validation for P21, it would be useful to be able to target the SDTM folder and include at least DM, AE, and EX domains. These domains are essential for traceability in the validator. Additionally, it would be interesting to have the option to exclude some domains that will not be included in the zip.

**Comment by elimillera** [comment]
Add documentation with example using utils::zip to demo how you can accomplish this
