### ISSUE TITLE
< and > symbols are no longer considered illegal characters in variable and dataset labels

### ISSUE THREAD

**Issue by nash-delcamp-slp** [atorus-research/xportr#98]
Hi, According to the most recent [Study Data Technical Conformance Guide - Technical Specifications Document](https://www.fda.gov/regulatory-information/search-fda-guidance-documents/study-data-technical-conformance-guide-technical-specifications-document) section 3.3, 3.3.5, and 3.3.7, the less than and greater than characters are no longer illegal characters in variable and dataset labels. So the regex that checks for illegal characters in `xpt_validate()` and `xportr_write()` could be updated from `"[<>]|[^[:ascii:]]"` to `"[^[:ascii:]]"`.

**Comment by bms63** [comment]
Thank you @nash-delcamp-slp !  We are working towards a new release of xportr in the coming months.  I have added this to our Project Board to work on
